# Generated by Django 5.2.13 on 2026-04-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_expediteur', models.CharField(max_length=100)),
                ('nom_destinataire', models.CharField(max_length=100)),
                ('adresse_livraison', models.CharField(max_length=255)),
                ('telephone_destinataire', models.CharField(max_length=20)),
                ('description_colis', models.TextField()),
                ('poids_colis', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prix_livraison', models.DecimalField(decimal_places=2, max_digits=8)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
